### ISSUE TITLE
Performance Hit

### ISSUE THREAD

**Issue by brucethemoose** [Sielfyr/Characteristic#1]
First of all, I love this mod!

But I got to mid-game, and noticed that (according to Dub's Performance Analyzer) it has a considerable performance hit. 

![Characteristic](https://user-images.githubusercontent.com/8422224/92979776-c0b03580-f461-11ea-9f64-4359213c4475.png)

Removing it takes me from ~70 TPS to more like 80-90, and the impact is more dramatic once I remove some other performance-heavy mods.  

I'm not sure if this is a bug or if it's just an unavoidable consequence for adding so many stats.

**Comment by brucethemoose** [comment]
On second thought, that reading could be misleading. I'll test Characteristic with an autotest colony in a bit.

**Comment by Sielfyr** [comment]
Hey! 
I checked what did this function in my file, it's a transpiler that add few line instruction.
I have a high doubt even in late game it can hit the performance that high, I suspect it show the impact for the whole function and not just my patch, it would make way more sense since it's the function that check for pawn stats and with your amount of pawn it should be called often.
To give you more insigth, my patch here in term of performence is basically the one for a single hediff, when in the whole function, it check for stats change in every hediff of the pawn.

**Comment by brucethemoose** [comment]
Yeah thats what I suspected, thanks!
